export {default as Dashboard} from "./dashboard/dashboard"
export {default as Login} from "./login/login"
export {default as Upload} from "./upload/upload"
export {default as Register} from "./register/register"
export {default as Homex} from "./homex/homex"