export {default as LoginTitle} from "./loginTitle/loginTitle";
export {default as BG} from "./background/background";
export {default as LoginButton} from "./loginButton/loginButton";
export {default as LoginText} from "./loginText/loginText";
export {default as Logo} from "./logo/logo";
export {default as RegisterTitle} from "./registerTitle/registerTitle";
export {default as RegisterButton} from "./registerButton/registerButton"
export {default as Add} from "./add/add"
export {default as Heart} from "./heart/heart"
export {default as Logout} from "./logout/logout"
export {default as Profile} from "./profile/profile"
export {default as BigSquare} from "./bigSquare/bigSquare"
export {default as LittleSquare} from "./littleSquare/littleSquare"
export {default as UploadButton} from "./uploadBtn/uploadBtn"
export {default as UploadText} from "./uploadText/uploadText"
export {default as UploadImg} from "./uploadimg/uploadimg"
export {default as AddTitle} from "./addTitle/addTitle"
export {default as UName} from "./uName/uName"
export {default as Describe} from "./describe/describe"
export {default as Dog} from "./dog/dog"
export {default as SaveButton} from "./saveBtn/saveBtn"
export {default as Exit} from "./exit/exit"
export {default as Tattoo} from "./tattoo/tattoo"
export {default as Options} from "./options/options"
export {default as Search} from "./search/search"
export {default as HomeBanner} from "./homeBanner/homeBanner"
export {default as HomeText} from "./homeText/homeText"
export {default as DarkLogo} from "./darkLogo/darkLogo"
export {default as LoginA} from "./loginA/loginA"
export {default as Cheers} from "./cheers/cheers"
export {default as Chanel} from "./chanel/chanel"
export {default as Inspire} from "./inspire/inspire"
export {default as Create} from "./create/create"
export {default as Ideas} from "./ideas/ideas"